### PR TITLE
Improved Nightfall data (and improved specs)

### PR DESCRIPTION
**Pull request by aergonaut**
Firstly: thanks so much for making this library! I found this from wanting to make a chat bot for my clan's Slack team to give us easy access to stuff like the Nightfall or Xur's inventory. That led me to lita-destiny and this library!

I know there's a lot of changes in this PR, so let me explain. I hope I'm not being too intrusive, but if I am, please let me know and I can scale back my changes. :bow: 
#### Changes to Destiny::Advisors#nightfall

This change is the main reason I wanted to submit this PR. I noticed that with the current code, the data for the Nightfall returns all of the possible skulls for Nightfall, rather than the specific ones that are active for the current week's Nightfall. I also noticed that the data does not return which strike is the Nightfall, just a generic description of the Nightfall. I assume this is because Bungie changed how their API works since Taken King was released.

I modified the `nightfall` method to return some extra information when `raw = false`. The result now includes an `:activeSkulls` key which is an Array of the display names of the skulls active for the current week. It also includes a `:specificActivity` key which is another Hash containing the name and description of the specific strike for the current week.
#### Improvements to the test suite

I noticed there weren't that many tests, so I took the liberty of expanding them to cover the new code I added.

I have added [VCR](https://github.com/vcr/vcr) and [WebMock](https://github.com/bblimke/webmock) to the RSpec config. In case you haven't heard of these gems before, VCR allows you to record and replay HTTP interactions during tests, and WebMock lets you stub HTTP requests. So that lets me record interactions with the real Bungie API and then replay them back during testing.

I also added [Dotenv](https://github.com/bblimke/webmock) so that sensitive info like Bungie API keys can be kept out of the repo and read in from environment variables during testing.

I also reorganized the `spec/` directory so that it mirrors the directory structure of the project; i.e. modules in `lib/` have their specs in `spec/lib/`

### CODE REVIEW

**Comment by pdai1y** [comment]
@aergonaut this is totally awesome!

Thank you so much for taking an interest in this gem, I'm really happy to see others using it and taking the time out to help the development of it.

I've reviewed your pull request and I'll get it merged right away. Once I get it into the main branch I'll make sure to update the version of the gem and get it published to RubyGems!

**Comment by aergonaut** [comment]
@PDaily thanks! :smiley:

Once you get the RubyGems version updated, I'll probably make a PR to lita-destiny too, to use the expanded Nightfall info in the !nightfall command.

**Comment by pdai1y** [comment]
Hehe, I seem to have beaten you to the punch on that. Build is failing right now, but that's because Bungie only allows valid API calls to their servers. I might have to replicate what you did here for the testing :P

**Comment by aergonaut** [comment]
@PDaily fair enough!

**Pull request merged**
